version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  air-data-service:
    build:
      context: ./backend/air-data-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres
    restart: on-failure

  anomaly-detection-service:
    build:
      context: ./backend/anomaly-detection-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - postgres
    restart: on-failure

  data-storage-service:
    build:
      context: ./backend/data-storage-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
    restart: on-failure

  notification-service:
    build:
      context: ./backend/notification-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
    restart: on-failure

  script-runner-service:
    build:
      context: ./backend/script-runner-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - postgres
    restart: on-failure
