server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/airqualitydb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: kafka:9092
  topic:
    air-data: air-data
  group-id: data-storage-group

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true