server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airqualitydb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kafka:
  bootstrap-servers: localhost:9092
  topic:
    air-data: air-data
  group-id: data-storage-group
