spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anomalydb
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083
